<a href="https://colab.research.google.com/github/Prashantkumartalan43/Exercise/blob/main/python_basics_week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Object Oriented Programming

class ClassName:
  pass

In [ ]:
class Customer:
  pass

customer1 = Customer()
print(customer1)

In [ ]:
class Customer:
  name = "Rahul"

customer1 = Customer()
print(customer1.name)

Rahul


In [ ]:
class Customer:
  def __init__(self, name):
    self.name = name

In [ ]:
customer1 = Customer("Rahul")
customer2 = Customer("Amit")

print(customer1.name)
print(customer2.name)

Rahul
Amit


In [ ]:
class Customer:
  def __init__(self, name, city, purchase):
    self.name = name
    self.city = city
    self.purchase = purchase

In [ ]:
customer = Customer(
    "Rahul",
    "Delhi",
    50000
)

print(customer.name)
print(customer.city)
print(customer.purchase)

Rahul
Delhi
50000


In [ ]:
class Customer:
  def __init__(self, name):
    self.name = name

  def greet(self):
    print(f"Hello {self.name}")

customer = Customer("Rahul")
customer.greet()


Hello Rahul


In [ ]:
class Customer:
  def __init__(self, name, purchase):

    self.name = name
    self.purchase = purchase

  def customer_type(self):

    if self.purchase > 50000:
      return "Premium"

    return "Regular"

In [ ]:
customer = Customer("Rahul", 60000)

print(customer.customer_type())

Premium


In [ ]:
c1 = Customer("Rahul", 60000)
c2 = Customer("Amit", 72000)

In [ ]:
class Customer:
  def __init__(self, name, salary):

    self.name = name
    self.salary = salary

  def annual_salary(self):
    return self.salary * 12

c1 = Customer("Rahul", 50000)

print(c1.annual_salary())

600000


In [ ]:
class Product:
  def __init__(self, name, price):

    self.name = name
    self.price = price

  def discounted_price(self, discount):

    return(self.price * (1 - discount / 100))

In [ ]:
product = Product("Laptop", 50000)

print(product.discounted_price(10))

45000.0


In [ ]:
class SalesRecord:
  def __init__(self, month, sales):

    self.month = month
    self.sales = sales

  def display(self):

    print(self.month,
          self.sales)

record = SalesRecord("January", 15000)
print(record.display())

January 15000
None


In [ ]:
import math

In [ ]:
print(math.sqrt(25))

5.0


In [ ]:
radius = 5

area = math.pi * radius ** 2

print(f"{area:.2f}")

78.54


In [ ]:
import random

In [ ]:
print(random.randint(1, 10))

2


In [ ]:
import datetime

In [ ]:
today = datetime.date.today()

print(today)

2026-06-13


In [ ]:
now = datetime.datetime.now()

print(now)

2026-06-13 17:43:16.510316


In [ ]:
print(today.year)

2026


In [ ]:
customers = ["Rahul", "Amit", "Priya", "Neha"]

winner = random.choice(customers)

print(winner)

Rahul


In [ ]:
# numpy

pip install numpy

In [ ]:
import numpy as np

In [ ]:
sales = [12000, 15000, 18000, 14000]

sales = np.array([12000, 15000, 18000, 14000])

print(sales)

[12000 15000 18000 14000]


In [ ]:
print(sales.shape)
print(sales.size)
print(sales.dtype)
print(sales.ndim)

(4,)
4
int64
1


In [ ]:
print(sales[0])
print(sales[-1])
print(sales[1:3])

12000
14000
[15000 18000]


In [ ]:
sales = np.array([100, 200, 300])

new_sales = sales * 2

print(new_sales)

[200 400 600]


In [ ]:
salaries = np.array([10000, 20000, 30000])

new_salaries = salaries * 1.2

print(new_salaries)

[12000. 24000. 36000.]


In [ ]:
print(np.sum(salaries))
print(np.mean(salaries))
print(np.min(salaries))
print(np.max(salaries))

60000
20000.0
10000
30000


In [ ]:
print(np.zeros(5))
print(np.ones(5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [ ]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
print(np.arange(1, 11, 2))
print(np.arange(2,11, 2))

[1 3 5 7 9]
[ 2  4  6  8 10]


In [ ]:
marks = np.array([[78,85,90],
                  [67,88,92],
                  [95,81,79]])

print(marks)

[[78 85 90]
 [67 88 92]
 [95 81 79]]


In [ ]:
print(marks.shape)
print(marks[0][1])
print(marks[0, 1])
print(f"{np.mean(marks):.2f}")

(3, 3)
85
85
83.89


In [ ]:
print(np.array(
    [1,2,"hello"]).dtype
)

<U21


In [ ]:
data = np.array([1,2,3,4,5,6])

print(data.shape)

(6,)


In [ ]:
data = data.reshape(2, 3)

print(data)
print(data.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
print(data[:3])

[[1 2 3]
 [4 5 6]]


In [ ]:
print(data.ndim)
print(np.mean(data))

2
3.5


In [ ]:
print(np.sum(data))
print(np.sum(data, axis=0))
print(np.sum(data, axis=1))

21
[5 7 9]
[ 6 15]


In [1]:
import pandas as pd

In [ ]:
sales = pd.Series([12000, 15000, 18000, 14000])

print(sales)

0    12000
1    15000
2    18000
3    14000
dtype: int64


In [ ]:
data = {
    "Name": ["Rahul", "Amit", "Priya"],
    "Age": [21, 22, 20],
    "City": ["Delhi", "Mumbai", "Pune"]
}

df = pd.DataFrame(data)

print(df)

    Name  Age    City
0  Rahul   21   Delhi
1   Amit   22  Mumbai
2  Priya   20    Pune


In [ ]:
print(df.head(1))
print(df.tail(1))

    Name  Age   City
0  Rahul   21  Delhi
    Name  Age  City
2  Priya   20  Pune


In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    3 non-null      object
 1   Age     3 non-null      int64 
 2   City    3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes
None


In [ ]:
print(df.describe())

        Age
count   3.0
mean   21.0
std     1.0
min    20.0
25%    20.5
50%    21.0
75%    21.5
max    22.0


In [ ]:
print(df["Name"])
print(df[["Name", "Age"]])

0    Rahul
1     Amit
2    Priya
Name: Name, dtype: object
    Name  Age
0  Rahul   21
1   Amit   22
2  Priya   20


In [ ]:
print(df.loc[0])

Name    Rahul
Age        21
City    Delhi
Name: 0, dtype: object


In [ ]:
print(df.iloc[1])

Name      Amit
Age         22
City    Mumbai
Name: 1, dtype: object


In [ ]:
data = {
    "Sales":[12000,15000,18000,14000]
}

df = pd.DataFrame(data)

In [ ]:
print(df["Sales"].sum())
print(df["Sales"].mean())
print(df["Sales"].min())
print(df["Sales"].max())

59000
14750.0
12000
18000


In [ ]:
df = pd.read_csv("sample_data/california_housing_test.csv")

print(df.head())

   longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.05     37.37                27.0       3885.0           661.0   
1    -118.30     34.26                43.0       1510.0           310.0   
2    -117.81     33.78                27.0       3589.0           507.0   
3    -118.36     33.82                28.0         67.0            15.0   
4    -119.67     36.33                19.0       1241.0           244.0   

   population  households  median_income  median_house_value  
0      1537.0       606.0         6.6085            344700.0  
1       809.0       277.0         3.5990            176500.0  
2      1484.0       495.0         5.7934            270500.0  
3        49.0        11.0         6.1359            330000.0  
4       850.0       237.0         2.9375             81700.0  


In [2]:
import pandas as pd

data = {
    "Name": [
        "Rahul",
        "Amit",
        None,
        "Priya",
        "Rahul"
    ],

    "Age": [
        21,
        None,
        22,
        20,
        21
    ],

    "City": [
        "Delhi",
        "Mumbai",
        "Pune",
        None,
        "Delhi"
    ]
}

df = pd.DataFrame(data)

print(df)

    Name   Age    City
0  Rahul  21.0   Delhi
1   Amit   NaN  Mumbai
2   None  22.0    Pune
3  Priya  20.0    None
4  Rahul  21.0   Delhi


In [3]:
print(df.isnull())

    Name    Age   City
0  False  False  False
1  False   True  False
2   True  False  False
3  False  False   True
4  False  False  False


In [4]:
print(df.isnull().sum())

Name    1
Age     1
City    1
dtype: int64


In [5]:
clean_df = df.dropna()

print(clean_df)

    Name   Age   City
0  Rahul  21.0  Delhi
4  Rahul  21.0  Delhi


In [6]:
df["Age"] = df["Age"].fillna(0)

In [7]:
mean_age = df["Age"].mean()

df["Age"] = df["Age"].fillna(mean_age)

In [8]:
df["City"] = df["City"].fillna(
    "Unknown"
)

In [9]:
print(df.duplicated())

0    False
1    False
2    False
3    False
4     True
dtype: bool


In [10]:
print(df.duplicated().sum())

1


In [11]:
df = df.drop_duplicates()

In [12]:
data = {
    "Name":[
        "Rahul",
        "Amit",
        "Priya"
    ],

    "Sales":[
        12000,
        18000,
        15000
    ]
}

In [13]:
df = pd.DataFrame(data)

In [14]:
print(
    df[
        df["Sales"] > 15000
    ]
)

   Name  Sales
1  Amit  18000


In [15]:
filtered = df[
    (df["Sales"] >= 12000)
    &
    (df["Sales"] <= 17000)
]

print(filtered)

    Name  Sales
0  Rahul  12000
2  Priya  15000


In [16]:
data = {
    "Sales":[
        18000,
        12000,
        21000,
        15000
    ]
}

In [17]:
print(
    df.sort_values(
        by="Sales"
    )
)

    Name  Sales
0  Rahul  12000
2  Priya  15000
1   Amit  18000


In [18]:
print(
    df.sort_values(
        by="Sales",
        ascending=False
    )
)

    Name  Sales
1   Amit  18000
2  Priya  15000
0  Rahul  12000


In [19]:
df.rename(
    columns={
        "Name":"Customer_Name"
    },
    inplace=True
)

In [21]:
print(df.dtypes)

Customer_Name    object
Sales             int64
dtype: object


In [23]:
print("Rows:",
      len(df))

print("Missing:")
print(
    df.isnull().sum()
)

print("Duplicates:",
      df.duplicated().sum())

Rows: 3
Missing:
Customer_Name    0
Sales            0
dtype: int64
Duplicates: 0
