<a href="https://colab.research.google.com/github/Prashantkumartalan43/Exercise/blob/main/python_basics_week3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Object Oriented Programming

class ClassName:
  pass

In [ ]:
class Customer:
  pass

customer1 = Customer()
print(customer1)

In [ ]:
class Customer:
  name = "Rahul"

customer1 = Customer()
print(customer1.name)

Rahul


In [ ]:
class Customer:
  def __init__(self, name):
    self.name = name

In [ ]:
customer1 = Customer("Rahul")
customer2 = Customer("Amit")

print(customer1.name)
print(customer2.name)

Rahul
Amit


In [ ]:
class Customer:
  def __init__(self, name, city, purchase):
    self.name = name
    self.city = city
    self.purchase = purchase

In [ ]:
customer = Customer(
    "Rahul",
    "Delhi",
    50000
)

print(customer.name)
print(customer.city)
print(customer.purchase)

Rahul
Delhi
50000


In [ ]:
class Customer:
  def __init__(self, name):
    self.name = name

  def greet(self):
    print(f"Hello {self.name}")

customer = Customer("Rahul")
customer.greet()


Hello Rahul


In [ ]:
class Customer:
  def __init__(self, name, purchase):

    self.name = name
    self.purchase = purchase

  def customer_type(self):

    if self.purchase > 50000:
      return "Premium"

    return "Regular"

In [ ]:
customer = Customer("Rahul", 60000)

print(customer.customer_type())

Premium


In [ ]:
c1 = Customer("Rahul", 60000)
c2 = Customer("Amit", 72000)

In [ ]:
class Customer:
  def __init__(self, name, salary):

    self.name = name
    self.salary = salary

  def annual_salary(self):
    return self.salary * 12

c1 = Customer("Rahul", 50000)

print(c1.annual_salary())

600000


In [ ]:
class Product:
  def __init__(self, name, price):

    self.name = name
    self.price = price

  def discounted_price(self, discount):

    return(self.price * (1 - discount / 100))

In [ ]:
product = Product("Laptop", 50000)

print(product.discounted_price(10))

45000.0


In [ ]:
class SalesRecord:
  def __init__(self, month, sales):

    self.month = month
    self.sales = sales

  def display(self):

    print(self.month,
          self.sales)

record = SalesRecord("January", 15000)
print(record.display())

January 15000
None


In [ ]:
import math

In [ ]:
print(math.sqrt(25))

5.0


In [ ]:
radius = 5

area = math.pi * radius ** 2

print(f"{area:.2f}")

78.54


In [ ]:
import random

In [ ]:
print(random.randint(1, 10))

2


In [ ]:
import datetime

In [ ]:
today = datetime.date.today()

print(today)

2026-06-13


In [ ]:
now = datetime.datetime.now()

print(now)

2026-06-13 17:43:16.510316


In [ ]:
print(today.year)

2026


In [ ]:
customers = ["Rahul", "Amit", "Priya", "Neha"]

winner = random.choice(customers)

print(winner)

Rahul


In [1]:
# numpy

pip install numpy

In [2]:
import numpy as np

In [3]:
sales = [12000, 15000, 18000, 14000]

sales = np.array([12000, 15000, 18000, 14000])

print(sales)

[12000 15000 18000 14000]


In [5]:
print(sales.shape)
print(sales.size)
print(sales.dtype)
print(sales.ndim)

(4,)
4
int64
1


In [7]:
print(sales[0])
print(sales[-1])
print(sales[1:3])

12000
14000
[15000 18000]


In [8]:
sales = np.array([100, 200, 300])

new_sales = sales * 2

print(new_sales)

[200 400 600]


In [9]:
salaries = np.array([10000, 20000, 30000])

new_salaries = salaries * 1.2

print(new_salaries)

[12000. 24000. 36000.]


In [10]:
print(np.sum(salaries))
print(np.mean(salaries))
print(np.min(salaries))
print(np.max(salaries))

60000
20000.0
10000
30000


In [12]:
print(np.zeros(5))
print(np.ones(5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [13]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
print(np.arange(1, 11, 2))
print(np.arange(2,11, 2))

[1 3 5 7 9]
[ 2  4  6  8 10]


In [18]:
marks = np.array([[78,85,90],
                  [67,88,92],
                  [95,81,79]])

print(marks)

[[78 85 90]
 [67 88 92]
 [95 81 79]]


In [24]:
print(marks.shape)
print(marks[0][1])
print(marks[0, 1])
print(f"{np.mean(marks):.2f}")

(3, 3)
85
85
83.89


In [26]:
print(np.array(
    [1,2,"hello"]).dtype
)

<U21


In [27]:
data = np.array([1,2,3,4,5,6])

print(data.shape)

(6,)


In [29]:
data = data.reshape(2, 3)

print(data)
print(data.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [31]:
print(data[:3])

[[1 2 3]
 [4 5 6]]


In [37]:
print(data.ndim)
print(np.mean(data))

2
3.5


In [42]:
print(np.sum(data))
print(np.sum(data, axis=0))
print(np.sum(data, axis=1))

21
[5 7 9]
[ 6 15]
